version: '2.4'

services:
    php:
        build:
            context: .
        command: php-fpm
        volumes:
            - .:/var/www/html
            - ./vendor:/var/www/html/vendor
        ports:
            - "9000:9000"
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
